name: everdo_app
description: EverDo splash demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  flutter:
    sdk: flutter
 
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2 
  local_auth: ^3.0.0           
  provider: ^6.0.0           
  flutter_secure_storage: ^9.2.4
  dartz: ^0.10.1
          

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: UthmanTNB
      fonts:
        - asset: assets/font/UthmanTNB_v2-0.ttf
    - family: jomhuria
      fonts:
        - asset: assets/font/jomhuria-regular-full-org.ttf
    - family: PlaypenSansArabic
      fonts:
        - asset: assets/font/PlaypenSansArabic-Bold.ttf
        - asset: assets/font/PlaypenSansArabic-Light.ttf
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/font/Lalezar-Regular.ttf
        
       
        
   